image: Visual Studio 2019

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: WebApplication.sln
  verbosity: minimal
  
environment:
    COVERALLS_REPO_TOKEN:  
       secure: 1UceYDhaW68dS0kfYiprKqGuCrC9y8NK1

after_test: 
    - C:\ProgramData\chocolatey\lib\opencover.portable\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"%programfiles(x86)%\Microsoft Visual Studio\2019\Community\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:WebApplication.Services.Tests.dll" -output:coverage.xml
        
    - packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml