image: Visual Studio 2019

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: WebApplication.sln
  verbosity: minimal
  
environment:
    COVERALLS_REPO_TOKEN:  
       secure: 1UceYDhaW68dS0kfYiprKqGuCrC9y8NK1

after_test: 
    - dotnet test ./WebApplication.Services.Tests/WebApplication.Services.Tests.csproj --no-build /p:CollectCoverage=true
    - C:\ProgramData\chocolatey\lib\codecov\tools\codecov.exe -f .\WebApplication.Services.Tests\coverage.opencover.xml -t 2d12945c-f44b-4b62-ba0a-e1acd5f73179